--- #YAML:1.0
name:               Statistics-Robust
version:            0.02
abstract:           A Collection of Robust Statistical Methods
author:
    - Walter Szeliga <walter@geology.cwu.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::CDF:            0.1
    Math::Random:         0
    Math::Round:          0
    Test::More:           0
    Test::Number::Delta:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
